### ISSUE TITLE
How to get FEChasedown slab results

### ISSUE THREAD

**Issue by TM00** [TrimbleSolutionsCorporation/TSDRemotingAPIExamples#3]
Hi again :) 

I've installed TSD 2022 sp2 and the API works with it. I really like it thus far!! 

I've started with a simple multi-storey flat slab model in TSD and I am trying to get the FE chasedown slab nodal results. I'm interested in the `INodalMeshForces` for the slabs/panels in the model. It seems that I can get the meshforces for a slab/panel which has "mesh 2-way slabs in 3D analysis" ticked in TSD with the `FirstOrderLinear` `AnalysisType`. When I change the `AnalysisType` to `FEChaseDown` I get no meshforces from the model? Please advise if I'm doing something wrong or if there is another way to get the results for a `FEChaseDown` analysis? 

For reference, here's the code I'm currently testing (if you need more information please let me know):

Class to get the meshforces per AnalysisType:

```
        public static async Task runTest1(TSD.API.Remoting.Solver.AnalysisType analysisType)
        {

            if(analysisType == null)
            {
                analysisType = TSD.API.Remoting.Solver.AnalysisType.FirstOrderLinear;
            }

            Console.WriteLine("------------------------------------------------- ");
            Console.WriteLine("----------     Running Test 1         ----------- ");
            Console.WriteLine("----------     "+analysisType+"         ----------- ");
            Console.WriteLine("------------------------------------------------- ");

            

            TSD.API.Remoting.Structure.IModel structuralModel = await InfoGetter.GetTSDInfoAsync();

            Console.WriteLine("got structuralModel "+ structuralModel);

            TSD.API.Remoting.Solver.IModel solverModel = await ResultGetter.getSolverModelAsync(
                structuralModel, analysisType);

            Console.WriteLine("got solverModel " + solverModel);


            TSD.API.Remoting.Solver.IAnalysisResults analysisResults = await ResultGetter.getResultsAsync(solverModel);

            Console.WriteLine("got analysisResults " + analysisResults);


            TSD.API.Remoting.Solver.IAnalysis3DResults analysisResults3D = await ResultGetter.get3DResultsAsync(analysisResults);

            Console.WriteLine("got analysisResults3D " + analysisResults3D);


            List<Guid> solvedLoadingIds = await ResultGetter.getSolvedLoadingIDsAsync(analysisResults3D);

            Console.WriteLine("got solvedLoadingIds " + solvedLoadingIds);


            List<TSD.API.Remoting.Loading.ILoadingCase> allLoadCasesCombs = await ResultGetter.getModelLoadCasesCombinationsAsync(structuralModel);

            Console.WriteLine("got allLoadCasesCombs " + allLoadCasesCombs);


            List<TSD.API.Remoting.Loading.ILoadingCase> solvedLoadCasesCombs = await ResultGetter.getSolvedLoadCasesAsync(
                allLoadCasesCombs, solvedLoadingIds);

            Console.WriteLine("got solvedLoadCasesCombs " + solvedLoadCasesCombs);


            Console.WriteLine("Getting meshforces");

            foreach (var sc in solvedLoadCasesCombs)
            {
                Console.WriteLine("solvedLoadCase: " + sc);

                List<TSD.API.Remoting.Solver.INodalMeshForces> meshForces = await ResultGetter.getNodalMeshForces(analysisResults3D, sc.Id);

                Console.WriteLine("#nodes " + meshForces.Count);

                if (meshForces.Any())
                {

                    var mf0 = meshForces[0];

                    Console.WriteLine("meshforce 0 "+mf0.PanelForces);

                }


            }

        }

```
  

Helper class - ResultGetter:

```
    internal class ResultGetter
    {


        static IEnumerable<TSD.API.Remoting.Solver.AnalysisType> ValidAnalysisTypes() => new[]
         {
                TSD.API.Remoting.Solver.AnalysisType.None,
                TSD.API.Remoting.Solver.AnalysisType.FirstOrderLinear,
                TSD.API.Remoting.Solver.AnalysisType.FirstOrderNonLinear,
                TSD.API.Remoting.Solver.AnalysisType.SecondOrderLinear,
                TSD.API.Remoting.Solver.AnalysisType.SecondOrderNonLinear,
                TSD.API.Remoting.Solver.AnalysisType.FEChaseDown
         };



        public static async Task<TSD.API.Remoting.Solver.IModel> getSolverModelAsync(
            TSD.API.Remoting.Structure.IModel structuralModel,
            TSD.API.Remoting.Solver.AnalysisType analysisType)
        {
            var solverModels = await structuralModel.GetSolverModelsAsync(ValidAnalysisTypes());
            foreach (TSD.API.Remoting.Solver.IModel sm in solverModels)
            {
                if (sm.AnalysisType == analysisType)
                {
                    return sm;
                }

            }
            return null;
        }



        public static async Task<TSD.API.Remoting.Solver.IAnalysisResults> getResultsAsync(
               TSD.API.Remoting.Solver.IModel solverModel)
        {
            return await solverModel.GetResultsAsync();

        }

        public static async Task<TSD.API.Remoting.Solver.IAnalysis3DResults> get3DResultsAsync(
               TSD.API.Remoting.Solver.IAnalysisResults analysisResults)
        {
            return await analysisResults.GetAnalysis3DAsync();

        }

        public static async Task<List<Guid>> getSolvedLoadingIDsAsync(
            TSD.API.Remoting.Solver.IAnalysis3DResults analysisResults3D)
        {
            var solvedLoading = (await analysisResults3D.GetSolvedLoadingIdsAsync()).ToList();

            if (solvedLoading.Any())
            {

                String solvedLoadingIds = "getSolvedLoadingIDsAsync: ";
                foreach (var sl in solvedLoading)
                {
                    solvedLoadingIds += sl + "; \n";

                }
                Console.Write(solvedLoadingIds);
            }


                return solvedLoading;
        }

        public static async Task<List<TSD.API.Remoting.Loading.ILoadingCase>> getModelLoadCasesCombinationsAsync(
           TSD.API.Remoting.Structure.IModel structuralModel)
        {

            var loadingCases = (await structuralModel.GetLoadcasesAsync(null)).Cast<TSD.API.Remoting.Loading.ILoadingCase>().ToList();
            loadingCases.AddRange((await structuralModel.GetCombinationsAsync(null)).Cast<TSD.API.Remoting.Loading.ILoadingCase>());

            String loadcasesCombs = "loadcasesCombs: ";
            foreach (var sl in loadingCases)
            {
                loadcasesCombs += sl.Name + ", " + sl.Id + "; \n";

            }
            Console.Write(loadcasesCombs);



            return loadingCases;
        }

        public static async Task<List<TSD.API.Remoting.Loading.ILoadingCase>> getSolvedLoadCasesAsync(
          List<TSD.API.Remoting.Loading.ILoadingCase> allLoadCases,
          List<Guid> solvedLoadcaseIds)
        {


            List<TSD.API.Remoting.Loading.ILoadingCase> solvedList = new List<TSD.API.Remoting.Loading.ILoadingCase>();

            String s = "getSolvedLoadCasesAsync: \n";

            foreach (var sl in solvedLoadcaseIds)
            {

                for (int i = 0; i < allLoadCases.Count; i++)
                {
                    TSD.API.Remoting.Loading.ILoadingCase lcsi = allLoadCases[i];
                    if (lcsi.Id == sl)
                    {
                 //       Console.WriteLine("got lcsi!! ");
                        solvedList.Add(lcsi);
                    }
                }

          //      s += "id: " + sl + " " + lcs + "\n";

            }

            foreach (var sl in solvedList)
            {
                s += "" + sl + "\n";

            }
            Console.Write(" " + s);

            return solvedList;
        }


        public static async Task<List<TSD.API.Remoting.Solver.INodalMeshForces>> getNodalMeshForces(
         TSD.API.Remoting.Solver.IAnalysis3DResults analysisResults3D,
         Guid loadcaseId
         )
        {
            var nodalMeshForces = await analysisResults3D.GetNodalMeshForcesAsync(loadcaseId, null);

            return nodalMeshForces.ToList();
        }


    }
```

I've tested it with a TSD model which has one level ticked as "mesh 2-way slabs in 3D analysis". Here is shortened output for both FistOrderLinear and FEChasedown AnalysisTypes (Note the difference in the last lines where the #nodes is displayed):

------------------------------------------------- 
----------     Running Test 1         ----------- 
----------     FirstOrderLinear         ----------- 
------------------------------------------------- 
Testing TSD....
 
got instances....
Members in the model: 35
got structuralModel TSD.API.Remoting.Structure.Model
got solverModel FirstOrderLinear - (efc03a99-1de8-4349-8e55-186f9a0e7551)
got analysisResults TSD.API.Remoting.Solver.AnalysisResults
got analysisResults3D TSD.API.Remoting.Solver.Analysis3DResults
getSolvedLoadingIDsAsync: 259a57f0-3a75-4455-b89a-788094adc191; 
727d9805-e26f-49a1-91e0-457f5fd352d1; 

got solvedLoadingIds System.Collections.Generic.List`1[System.Guid]
loadcasesCombs: 1 Self weight - excluding slabs, 259a57f0-3a75-4455-b89a-788094adc191; 
2 Slab self weight, 727d9805-e26f-49a1-91e0-457f5fd352d1; 
1 (Final) STR_{1}-1.35G+1.5Q+1.5RQ, 21078841-fe67-40a1-9a79-c90d124775d9; 
2 (Final) EQU_{1}-1.1G+1.5Q+1.5RQ, 0bacd6d3-3ee4-41fb-9981-8d1720629f22; 
got allLoadCasesCombs System.Collections.Generic.List`1[TSD.API.Remoting.Loading.ILoadingCase]
 getSolvedLoadCasesAsync: 
1 Self weight - excluding slabs
2 Slab self weight
1 (Final) STR_{1}-1.35G+1.5Q+1.5RQ
2 (Final) EQU_{1}-1.1G+1.5Q+1.5RQ
got solvedLoadCasesCombs System.Collections.Generic.List`1[TSD.API.Remoting.Loading.ILoadingCase]
Getting meshforces
solvedLoadCase: 1 Self weight - excluding slabs
#nodes 1182
meshforce 0 System.Collections.Generic.Dictionary`2[System.Int32,TSD.API.Remoting.Solver.IMeshForces]
solvedLoadCase: 2 Slab self weight
#nodes 1182
solvedLoadCase: 1 (Final) STR_{1}-1.35G+1.5Q+1.5RQ
#nodes 1182
meshforce 0 System.Collections.Generic.Dictionary`2[System.Int32,TSD.API.Remoting.Solver.IMeshForces]
solvedLoadCase: 2 (Final) EQU_{1}-1.1G+1.5Q+1.5RQ
#nodes 1182
meshforce 0 System.Collections.Generic.Dictionary`2[System.Int32,TSD.API.Remoting.Solver.IMeshForces]

------------------------------------------------- 
----------     Running Test 1         ----------- 
----------     FEChaseDown         ----------- 
------------------------------------------------- 
Testing TSD....
got instances....

Members in the model: 35
got structuralModel TSD.API.Remoting.Structure.Model
got solverModel FEChaseDown - (eb3d6ba0-a91c-48d0-aa90-e2fec13a7689)
got analysisResults TSD.API.Remoting.Solver.AnalysisResults
got analysisResults3D TSD.API.Remoting.Solver.Analysis3DResults
getSolvedLoadingIDsAsync: 259a57f0-3a75-4455-b89a-788094adc191; 
727d9805-e26f-49a1-91e0-457f5fd352d1; 
got solvedLoadingIds System.Collections.Generic.List`1[System.Guid]
loadcasesCombs: 1 Self weight - excluding slabs, 259a57f0-3a75-4455-b89a-788094adc191; 
2 Slab self weight, 727d9805-e26f-49a1-91e0-457f5fd352d1; 
1 (Final) STR_{1}-1.35G+1.5Q+1.5RQ, 21078841-fe67-40a1-9a79-c90d124775d9; 
2 (Final) EQU_{1}-1.1G+1.5Q+1.5RQ, 0bacd6d3-3ee4-41fb-9981-8d1720629f22; 
got allLoadCasesCombs System.Collections.Generic.List`1[TSD.API.Remoting.Loading.ILoadingCase]
 getSolvedLoadCasesAsync: 
1 Self weight - excluding slabs
2 Slab self weight
1 (Final) STR_{1}-1.35G+1.5Q+1.5RQ
2 (Final) EQU_{1}-1.1G+1.5Q+1.5RQ
got solvedLoadCasesCombs System.Collections.Generic.List`1[TSD.API.Remoting.Loading.ILoadingCase]
Getting meshforces
solvedLoadCase: 1 Self weight - excluding slabs
#nodes 0
solvedLoadCase: 2 Slab self weight
#nodes 0
solvedLoadCase: 1 (Final) STR_{1}-1.35G+1.5Q+1.5RQ
#nodes 0
solvedLoadCase: 2 (Final) EQU_{1}-1.1G+1.5Q+1.5RQ
#nodes 0

**Comment by MattSTrimble** [comment]
Hi

I believe the results you are trying to get are not yet available for FE Chasedown in the API.

Can I just check, are you trying to get results that can be seen within the TSD interface, possibly the "FE Results by Node" that can be shown in the Solver Model Data table?

Kind regards,
Matt Sharman
Trimble

**Comment by TM00** [comment]
Hi Matt, 

Thanks for getting back to me.  That's not ideal as I was hoping to use the FE results to create my own shear plots and determine peak shears for detailed punching checks.

As suggested I opened the tabular data and there definitely is results, see screenshot below:

![image](https://user-images.githubusercontent.com/23653718/182630714-bd7b3f0b-9675-4d75-a0e7-4db7ac9f9a8d.png)

As a sense check I added a couple of print statements and the First Order Linear analysis meshforces match that given in the tabular results in TSD.  See screenshot below. It just seems the FEChasedown analysis results are not available? 

![image](https://user-images.githubusercontent.com/23653718/182644614-8f701a8e-8d99-489a-84b8-df62a6dfc967.png)

![image](https://user-images.githubusercontent.com/23653718/182644807-89063a5a-093c-4a60-93c1-1ed41b77c930.png)



Is my approach correct to try and obtain the FE results? I'm new to the API so I may be looking in the wrong place for the results... The approach followed is the following:

1.  get the Document and associated structural model: `...Structure.IModel model = await document.GetModelAsync()`

2. get the solver model for the chosen `AnalysisType`: `structuralModel.GetSolverModelsAsync(ValidAnalysisTypes())`

3.  get the `IAnalysisResults`:  `solverModel.GetResultsAsync()`

4.  get the `IAnalysis3DResults`: `analysisResults.GetAnalysis3DAsync()`

5.  get the loading ids for solved loadcases:` (await analysisResults3D.GetSolvedLoadingIdsAsync()).ToList();`

6. get the nodal `Solver.INodalMeshForces`: `var nodalMeshForces = await analysisResults3D.GetNodalMeshForcesAsync(loadcaseId, null);`

If there's a different way to get the FE results please let me know. I'm currently thinking a workaround would be to export the nodal results from TSD to Excel and parse that into my script... Its not ideal but seems workable.

**Comment by MattSTrimble** [comment]
Hi Theo

I'm pleased to see that the First Order Linear results match those seen in the application.

You will not currently be able to get the FE Chasedown results, and I'll try to explain why...

The problem with FE Chasedown results is that they are calculated very differently to First Order Linear results. Structural Designer solves sub-models for FE Chasedown (whereas First Order Linear solves the whole model). It also only solves loadcases, rather than combinations. The application does not actually store the mesh results in the full model for FE Chasedown.

Sub-models are not yet available in the API. We may be able to enhance the API to make sub-models available. I will add this enhancement to our backlog. If we implement this, I believe it would be possible to get the mesh results for loadcases for FE Chasedown, though it would probably require a different method than getting the First Order Linear results.

Kind regards,
Matt

**Comment by TM00** [comment]
Hi Matt, 

Sorry for the radio silence. 

Thanks for the feedback, that makes sense as to why the FE results aren't shown. 

Please keep me updated on when/if this feature becomes available in the API. I trust it would be a while :)  

Kind regards
Theo
